name: CodeSweep

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  codesweep:
    name: CodeSweep Scan
    runs-on: ubuntu-latest
    steps:
      - name: CodeSweep Action
        uses: codesee-io/codesweep-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
